// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY05L8bidYPtoBg-XdU_wKwbGPrfVFrJg',
    appId: '1:620834351085:web:85fae201de81b11d99e9e4',
    messagingSenderId: '620834351085',
    projectId: 'poemapp-d0967',
    authDomain: 'poemapp-d0967.firebaseapp.com',
    storageBucket: 'poemapp-d0967.appspot.com',
    measurementId: 'G-EVKK6SE74X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUwXuUnemEV4UOLRttpEk0C4uOuFQFBxM',
    appId: '1:620834351085:android:29f681efacae979c99e9e4',
    messagingSenderId: '620834351085',
    projectId: 'poemapp-d0967',
    storageBucket: 'poemapp-d0967.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDRxgqTMvNApO6oOU-zNOVHjVDjNrGn7E',
    appId: '1:620834351085:ios:285bafc7a4fab32c99e9e4',
    messagingSenderId: '620834351085',
    projectId: 'poemapp-d0967',
    storageBucket: 'poemapp-d0967.appspot.com',
    iosClientId: '620834351085-v0odo22mk6cmrahad6ueb63qje2ls8ij.apps.googleusercontent.com',
    iosBundleId: 'com.example.poemApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDRxgqTMvNApO6oOU-zNOVHjVDjNrGn7E',
    appId: '1:620834351085:ios:285bafc7a4fab32c99e9e4',
    messagingSenderId: '620834351085',
    projectId: 'poemapp-d0967',
    storageBucket: 'poemapp-d0967.appspot.com',
    iosClientId: '620834351085-v0odo22mk6cmrahad6ueb63qje2ls8ij.apps.googleusercontent.com',
    iosBundleId: 'com.example.poemApp',
  );
}
